### ISSUE TITLE
DataID name property issue when processing AVHRR tarball

### ISSUE THREAD

**Issue by thja-pml** [pytroll/pygac-fdr#110]
We were recently trying to process a monthly tarball of AVHRR granules using pygac-fdr.  An issue arose where there was an error from the Writer.  We tracked this down to the '_get_encoding' section of the NetcdfWriter. 

Line 363 of writer.py is: 
```
scn_keys = set([key.name for key in scene.keys()]) 
```
which fails as the 'DataID' does not have a .name property.  I think this is because of the dictionary form of DataID.  

We are now doing test runs with a fix where the line is edited to:
```
try:
    scn_keys = set([key.name for key in scene.keys()]) 
else:
    scn_keys = set([key['name'] for key in scene.keys()]) 
```
which seems to be working for now.

**Comment by sfinkens** [comment]
This is fixed now and I'll make a release later today. Meanwhile you can try installing the latest version from master.
