### ISSUE TITLE
Unformatted log messages

### ISSUE THREAD

**Issue by carloshorn** [pytroll/pygac-fdr#20]
When processing files with `pygac-fdr-run`, I see many log messages like
>The following datasets were not created and may require resampling to be generated: DatasetID(name='3a', wavelength=(1.58, 1.61, 1.64), resolution=1050, polarization=None, calibration='reflectance', level=None, modifiers=()), DatasetID(name='3b', wavelength=(3.55, 3.74, 3.93), resolution=1050, polarization=None, calibration='brightness_temperature', level=None, modifiers=()), DatasetID(name='5', wavelength=(11.5, 12.0, 12.5), resolution=1050, polarization=None, calibration='brightness_temperature', level=None, modifiers=())

and
> Could not load dataset 'DatasetID(name='5', wavelength=(11.5, 12.0, 12.5), resolution=1050, polarization=None, calibration='brightness_temperature', level=None, modifiers=())': Unknown dataset: 5

together with a lot of Traceback info like 
> Traceback (most recent call last):
  File "venv/lib/python3.7/site-packages/satpy/readers/yaml_reader.py", line 781, in _load_dataset_with_area
    ds = self._load_dataset_data(file_handlers, dsid, **kwargs)
  File "venv/lib/python3.7/site-packages/satpy/readers/yaml_reader.py", line 666, in _load_dataset_data
    proj = self._load_dataset(dsid, ds_info, file_handlers, **kwargs)
  File "venv/lib/python3.7/site-packages/satpy/readers/yaml_reader.py", line 642, in _load_dataset
    projectable = fh.get_dataset(dsid, ds_info)
  File "venv/lib/python3.7/site-packages/satpy/readers/avhrr_l1b_gaclac.py", line 164, in get_dataset
    raise ValueError('Unknown dataset: {}'.format(key.name))
ValueError: Unknown dataset: 3b

These log messages originate from `satpy`, but they are not formatted meaning that they do not arrive with a severity, timestamp and module name. 

It would be great if these messages would also come with the same formatting as `pygac_fdr` messages, e.g.
> [INFO: 2020-08-03 20:56:52 : pygac_fdr] Appending GAC header

**Comment by sfinkens** [comment]
@carloshorn If you run `pygac-fdr-run` with `--log-all` then these messages should be prefixed properly. However, you will see more log messages from satpy as well.

**Comment by sfinkens** [comment]
I will turn off satpy log messages by default

**Comment by carloshorn** [comment]
Thanks a lot!
