### ISSUE TITLE
argument list too long for pygac-fdr-mda-collect

### ISSUE THREAD

**Issue by carloshorn** [pytroll/pygac-fdr#23]
Using `pygac-fdr-mda-collect` with a wild card expression works fine if the total number of files is small, but in most cases e.g. MetOp-A with 72887 NetCDF files, I get an argument list too long error from my shell.

A possible solution could be a `--read` argument to indicate that the filenames argument is a single text file containing all paths.

**Comment by djhoese** [comment]
I don't know anything about pygac but if this is a command line interface the argparse module allows for "from file" prefixes on arguments: https://docs.python.org/3/library/argparse.html#fromfile-prefix-chars

**Comment by carloshorn** [comment]
Yes, it is about a CLI using argparse, which unfortunately needs all files for a single execution as arguments, so `xargs` or `find` will not help. I had something like the `--files-from=FILE` argument of `rsync` in mind.
The `fromfile-prefix-chars` feature sounds like a good solution. I will give it a try.
Thanks!

**Comment by sfinkens** [comment]
@carloshorn Did you already look into this or should I?
