### ISSUE TITLE
read_gac is broken with latest satpy version

### ISSUE THREAD

**Issue by carloshorn** [pytroll/pygac-fdr#24]
The `Scene.readers` attribute became private (`Scene._readers`) in the latest version of `satpy`, therefore the following line does not work anymore:
https://github.com/pytroll/pygac-fdr/blob/9deca13fbffeddda7122af88a7fdc86945cfc708/pygac_fdr/reader.py#L50

See: https://github.com/pytroll/satpy/pull/1300

Maybe @mraspaud can help to define a clean way to access the filename info here.
If I understand the code correctly, the filename_info is generated here:
https://github.com/pytroll/satpy/blob/4aedf557e38dc155d640e67e35bdb1f5dbef55f3/satpy/readers/yaml_reader.py#L428-L429
Where it uses the `trollsift.parser.parse` function.

**Comment by djhoese** [comment]
I wonder if a public API for parsing filename information in Satpy would be useful. I think @gerritholl has needed it on multiple occasions.

**Comment by gerritholl** [comment]
Such a public API is something I've reimplemented myself multiple times over the past years, although never to the standards that Satpy is up to.  There's something along those lines in [typhon](https://github.com/atmtools/typhon)s `FileSet` too (see https://radiativetransfer.org/misc/typhon/doc/modules.html#filesets-and-handlers).  What I tend to need is to define not only a filename pattern but also a directory structure, such that I can easily loop through all files between times a and b, or request the next or previous file, with a generalised API.

**Comment by carloshorn** [comment]
If there are more users trying to extract filename information, an API should be an item in the satpy backlog. 
In this particular case, I think directly using the trollsift parser might be a very clean solution already.

**Comment by djhoese** [comment]
For an API specific to Satpy I was mainly thinking something that takes what reader is being checked and provides the filenames to parse. That way the user doesn't have to know anything about where reader configs come from and doesn't have to match the pattern to the filename. However, this requires parsing the filenames twice (once for getting the filename info alone, once for creating the Scene).

We could have something on the readers to make this easier and revert the `.readers -> ._readers` change. The `.file_handlers['gac_lac_l1b'][0].filename_info` part of the existing pygac code is pretty iffy. Although these are public attributes being accessed it isn't very flexible. I'm wondering if there is some higher level (more abstract) way of defining what's desired here. For example "give me the filename info for every file I provided".

**Comment by sfinkens** [comment]
> "give me the filename info for every file I provided"

That would be great! 

For the moment I could copy the pattern from `avhrr_l1b_gaclac.yaml` and parse the filename again using trollsift.
