### ISSUE TITLE
Add another level of verbosity to pygac-fdr-mda-collect

### ISSUE THREAD

**Issue by carloshorn** [pytroll/pygac-fdr#26]
I like to see the debug messages from the logger to get an idea about the progress, but the lines

https://github.com/pytroll/pygac-fdr/blob/9deca13fbffeddda7122af88a7fdc86945cfc708/bin/pygac-fdr-mda-collect#L37-L42

cause too much output.

Maybe the `'count'` action could be a good solution to control the verbosity level., see https://docs.python.org/3/library/argparse.html#action
```
parser.add_argument('--verbose', '-v', action='count', default=0)
```

**Comment by djhoese** [comment]
Here is what I do for a lot of my work applications:

```
    parser.add_argument('-v', '--verbose', dest='verbosity', action="count",
                        default=int(os.environ.get("VERBOSITY", 2)),
                        help='each occurrence increases verbosity 1 level through '
                             'ERROR-WARNING-Info-DEBUG (default Info)')
    args = parser.parse_args()

    levels = [logging.ERROR, logging.WARN, logging.INFO, logging.DEBUG]
    level = levels[min(3, args.verbosity)]
    logging.basicConfig(level=level)
```

**Comment by carloshorn** [comment]
Another idea would be a log message size limit, because the critical step in the application is
https://github.com/pytroll/pygac-fdr/blob/9deca13fbffeddda7122af88a7fdc86945cfc708/bin/pygac-fdr-mda-collect#L46
where `mda` is a pandas DataFrame of 1e4 to 1e5 rows.
This leads to a several MB long log message.

Something like `'%(message).1000s'` in the logging format declaration could do the job.

**Comment by djhoese** [comment]
Oh I should add that Satpy has a not-really-document TRACE level that can be added to the logging and is used by some of the low-level dependency tree stuff for when we really need detailed debug messages.

**Comment by sfinkens** [comment]
Ouch, good point. That's more a debugging leftover than a real log message. What if we remove that log message entirely and instead provide a small script `pygac-fdr-dump` to display the database contents. We could also add an argument `-n` to limit the number of lines displayed.
