### ISSUE TITLE
Add more metadata to nc files

### ISSUE THREAD

**Issue by sfinkens** [pytroll/pygac-fdr#6]
- ` sun_earth_distance_correction_factor to nc files`
- equator crossing longitude and UTC time
- describe quality flags using flag values/meanings
- include static correction factors (roll, pitch, yaw?)

**Comment by mraspaud** [comment]
Do we want to have the full header from the Gac file as Metadata somewhere also?

**Comment by sfinkens** [comment]
Good idea! Maybe we can put it in a separate netcdf group
