### ISSUE TITLE
Metop-C compatibility

### ISSUE THREAD

**Issue by carloshorn** [pytroll/pygac-fdr#80]
The current version cannot process Metop-C files.
I have a hot fix, but maybe let us discuss the options.

The problem is that there is no entry in the dictionary `metadata.TIME_COVERAGE` and therefore the program raises a `KeyError`.
Adding the Metop-C data would fix this issue, but I would suggest to change the following lines:

https://github.com/pytroll/pygac-fdr/blob/a270843176391316b444d42c0aa59574c446acc9/pygac_fdr/writer.py#L351-L353

in favour of using `TIME_COVERAGE.get(..., (None, None))`, and add the `time_cov_start` metadata optionally (same as `time_cov_end`). The missing `time_cov_start` should raise a warning, but it should not be the show stopper.

What do you think?

**Comment by carloshorn** [comment]
@sfinkens, I can setup the PR.

**Comment by sfinkens** [comment]
Closing, as MetOp-C has been added by #84. Opened a new issue for the attribute issue (#90).
